### ISSUE TITLE
[BUG] GameTime is capped to 60 FPS due to VSyncing.

### ISSUE THREAD

**Issue by mathew-odwyer** [mathew-odwyer/FinalEngine#107]
# Expected Behavior

The frame rate should be capped based on the user input [here]().

# Current Behavior

Frame Rate is always capped to a maximum of 60 FPS.

## Steps to Reproduce

1. [Launch](https://github.com/softwareantics/FinalEngine/blob/830c6dfae47abead6f99b966acc716312e38e966/FinalEngine.Launching/GameContainer.cs#L163) a game with above 60 FPS.
2. Set the windows title to the current frame rate inside the update function.
3. Run the application.

**Comment by mathewodwyer** [comment]
I fixed this ages okay, turns out OpenTK didn't have support for VSyncing in NativeWindow. See [here](https://github.com/opentk/opentk/pull/1311).
