### ISSUE TITLE
[FEATURE REQUEST] Resource Management

### ISSUE THREAD

**Issue by mathew-odwyer** [mathew-odwyer/FinalEngine#69]
# Description

I propose we develop a framework that allows the end-user to manage and retrieve preloaded resources. It's important to distinguish the difference between resource _loading_ and resource _management_:

- A resource loader would be responsible for loading a resource that would then be added to a resource manager (an example of a resource loader would be #68).
- A resource manager would be responsible for allowing the end-user to preload resources before their game starts, think of it as the Project Explorer in Unity or Visual Studio, where the resources are already prepackaged and given to the user to use when the game has started.

## The Why

It will allow the end-user simplicity, they wouldn't have to worry about whether they've already loaded a specific resource, they'll just be able to pass around an `IResourceManager` interface to retrieve resources that need to be used elsewhere in the code base.

## The How

Below is a simple interface I have in mind:

```csharp
public interface IResource : IDisposable
{
}

public interface IResourceLoader<T>
	where T : IResource
{
	// A "TextureLoader" would be "Texture" or "Image", something like that, "ModeLLoader"
        // would be "Model" or "Mesh", you get it.
	string GetSuffix();
	
	T LoadResource(string path);
}

public interface IResourceManager
{
	// This way users can get a loader to load resources during runtime.
	IResourceLoader<T> GetLoader<T>()
		where T : IResource;

	// Or they can retrieve resources that were preloaded, important to note here that
        // if they load resources outside of the manager, it wouldn't be managed by the resource
        // manger, so maybe a LoadResource<T>(string path) method would be better, I'm not sure.
	T GetResource<T>(string name)
				where T : IResource;

	// Lastly, this method would allow users to register their own resource loaders, which would
        // be really cool for plugin support later on :)
	void RegisterLoader<T>(IResourceLoader<T> loader)
		where T : IResource;
}
```

## Requirements

This issue would probably require at the very least #68 to be implemented, but I'd say we should wait until we also implement some sort of model loader as well 😄.

## Possible Issues

I don't see any possible issues, but I guarantee there's something obvious I'm overlooking 😆.

**Comment by mathew-odwyer** [comment]
Perhaps the resource manager could be responsible for loading resources with the correct loaders by resolving their respective suffixes (such as .bmp, .jpg, .png, etc). This will ensure the plugin-support compatibility _and_ it will also allow the manager to actually _manage_ the resources (for example, ensure that no resource is loaded more than once accidentally).

```csharp
public interface IResource : IDisposable
{
}

public interface IResourceLoader<T>
	where T : IResource
{
	// For a texture loader, this might be: png, jpg, etc.
	IEnumerable<string> GetSuffixes();
	
	T LoadResource(string path);
}

public interface IResourceManager
{
	void RegisterLoader<T>(IResourceLoader<T> loader)
		where T : IResource;
	
	// The user can then choose whether to specify the suffix, if they wanted too.
	// Just in case maybe there are two or more files with the same name but different suffixes.
        // The doManage boolean would be used to make it so the user can load a resource more than once, and it will not be managed by the resource manager. However, what happens if the resource has already been loaded? Hmm....
	void GetResource(string path, bool doManage = true)
		where T: IResource;
}
```

**Comment by mathew-odwyer** [comment]
Just a few things to note here, a bit of rambling but I need to keep this jotted down so:

- Resourcing scoping
  - When loading a new scene in a game, the user could set a "scope" for a list of resources to say, 2. Then when a scene is loaded tell the resource manager you wish to load all resources with a scope of 2.
- Reference counting
  - The resource manager should be able to keep track of how many times a resource is being referenced, this way, when the resource has zero references, the manager will dispose of the resource.
  - If we do this, it's important to note in the documentation that you _should not_ pass resources around and should instead use the resource manager to make use of reference counting, otherwise, what happens when a resource is disposed but an object requires it? unhandled exception 😢.
- Resources should probably have some sort of file format such as XML or JSON, this would also make it easier to implement a resource loader, as there would only be one class, that returns a resource interface, not multiple loaders doing separate jobs. Obviously this would just be a form of indirection and loading of the actual resources will be done elsewhere, but it will be easier to manage this way, hopefully.

**Comment by softwareantics** [comment]
GetResourceLoqder<T> where T : IResourceLoader

???

**Comment by softwareantics** [comment]
Hmm, but how will convert the resource to the correct type? This is frustrating ugh

**Comment by softwareantics** [comment]
ResolveResource<ITexture2D>?

**Comment by softwareantics** [comment]
The real issue I need to fix is that a resource can be any type - this probably means I need a resource manager for each individual type.

I don't know how I will be able to solve this without the use of some sort of service locator pattern...
